### ISSUE TITLE
Lots of warnings with debug on

### ISSUE THREAD

**Issue by rosswintle** [dartiss/bazalgette#8]
Hi David,

I saw this on Mastodon and thought I'd try it out.

I'm downloaded and installed from the develop branch (currently commit 8a1c990). When I added it to WordPress with wp-debug turned on I got a load of warnings in the dashboard:

`Warning: Undefined array key 0 in <path>/wp-content/plugins/bazalgette-develop/inc/clean.php on line 100`

Looks like you should check you have a regex match before working with it.

**Comment by dartiss** [comment]
Good spot, Ross - thank you! Yeah, I've not even got to the point of trying to use debug with it yet, but it seems a good time to do that.

I'll leave this open until I fix it as a reminder!

**Comment by dartiss** [comment]
Now fixed and will be pushed out in the next release.
