### ISSUE TITLE
Menu separators should not be removed

### ISSUE THREAD

**Issue by rosswintle** [dartiss/bazalgette#9]
Activating this plugin seems to remove the `.wp-menu-separator` elements which squished the menu up.

These separators should be preserved.

**Comment by rosswintle** [comment]
Ah. I found [the Alpha release note](https://github.com/dartiss/bazalgette/discussions/7) - this is a feature!

Interesting, I'm not sure this is something I would want. I like the separators.

**Comment by dartiss** [comment]
Hey Ross. Well spotted! It will be an option, but as I've not put a settings screen in yet, it's on by default for now.

As I understand it, separators are in core in the main menu but not sub-menus. However, I've seen plugins add their own sub-menu separators in. So, default behaviour will be for them to be left in main but removed from subs. Does this sound the right behaviour to you?

**Comment by dartiss** [comment]
BTW, there's a list of things that I've implemented here, in the Discussions... https://github.com/dartiss/bazalgette/discussions/7

**Comment by rosswintle** [comment]
Yeah, I found the eventually.

For me, personally, I think removing separators isn't something I'd want. But if it's an option then go for it I guess!

**Comment by dartiss** [comment]
Thanks Ross. I appreciate the feedback. I'll close this issue up, but please let me know if you have any other feedback.
